# Generated by Django 5.1 on 2024-09-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MD', '0003_department_studentid_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsManager',
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_deleted',
        ),
    ]
