# Generated by Django 5.1 on 2024-09-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MD', '0004_delete_studentsmanager_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.CharField(max_length=50),
        ),
    ]
